<a href="https://colab.research.google.com/github/MuntahaZaigham1/ds1/blob/master/p2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sys


In [0]:
def hypothesis(theta, X, n):
    h = np.ones((X.shape[0],1))
    theta = theta.reshape(1,n+1)
    for i in range(0,X.shape[0]):
        h[i]=float(np.matmul(theta, X[i]))
    h = h.reshape(X.shape[0])
    return h

In [0]:
def BGD(theta, alpha, num_iters, h, X, y, n):
    cost = np.ones(num_iters)
    for i in range(0,num_iters):
        theta[0] = theta[0]-((alpha/X.shape[0])*sum(np.square(h - y)))
        for j in range(1,n+1):
            theta[j] = theta[j] - (alpha/X.shape[0]) * sum((h-y) * X.transpose()[j])
        h = hypothesis(theta, X, n)
        cost[i] = (1/X.shape[0]) * 0.5 * sum(np.square(h - y))
    theta = theta.reshape(1,n+1)
    return theta, cost

In [0]:
def linear_regression(X, y, alpha, num_iters):
    n = X.shape[1]
    one_column = np.ones((X.shape[0],1))
    X = np.concatenate((one_column, X), axis = 1)
    # initializing the parameter vector...
    theta = np.zeros(n+1,dtype=object)
    print(theta)
    # hypothesis calculation....
    h = hypothesis(theta, X, n)
    # returning the optimized parameters by Gradient Descent...
    theta, cost = BGD(theta,alpha,num_iters,h,X,y,n)
    return theta, cost

In [82]:
data = np.loadtxt('/content/multivariateLRData.csv', delimiter=',')
#data = pd.read_csv("/content/multivariateLRData.csv") 
data = np.hstack(( np.ones((len(data), 1)), data))# adding x0

No_of_cols = data.shape[1]
X_train = data[:,range(0, No_of_cols - 1)] #feature set
y_train = data[:, [No_of_cols - 1]] #label set

print(X_train)


[[  1.  24. 100. 110.  73.]
 [  1.  19. 100.  78.  30.]
 [  1.  13.  88.  99.  99.]
 [  1.  21. 100.  68.  30.]
 [  1.  17.  90.  69.  36.]
 [  1.  10.  88.  22.  22.]
 [  1.  19.  94.  53.  17.]
 [  1.  14.  90.  37.  25.]
 [  1.  18. 100.  38.  13.]
 [  1.  18. 100.  38.  13.]
 [  1.   9.   0.   7.   7.]
 [  1.   6.  59.  33.  25.]
 [  1.   5.   0.   7.   7.]
 [  1.   4.  75.   8.   8.]
 [  1.   4.   0.   6.   6.]
 [  1.  24.  96. 140.  35.]
 [  1.  23.  92.  53.  25.]
 [  1.   9.  28.  31.  23.]
 [  1.   2.  94.  52.  17.]
 [  1.   6.  80.  15.  15.]
 [  1.   5.  25.   9.   9.]
 [  1.   0. 100.   0.   0.]
 [  1.   0. 100.   0.   0.]
 [  1.   8.  58.  37.  34.]
 [  1.  15.  77.  12.  12.]
 [  1.  11.  76.  28.  28.]
 [  1.  12.  55.  24.  20.]
 [  1.   4. 100.  11.  11.]
 [  1.  14.  94. 198.  24.]
 [  1.   2.  85.  11.   7.]
 [  1.   1.   0.   3.   3.]
 [  1.   4.  90.  20.  20.]
 [  1.   3.  90.  11.   8.]
 [  1.   5.   0.  10.   5.]
 [  1.   5. 100.   8.   8.]
 [  1.   0.   0.   3

In [0]:
# calling the principal function with learning_rate = 0.0001 and 
# num_iters = 300000
theta, cost = linear_regression(X_train, y_train,0.01, 1)

In [0]:
import matplotlib.pyplot as plt
cost = list(cost)
n_iterations = [x for x in range(1,300001)]
plt.plot(n_iterations, cost)
plt.xlabel('No. of iterations')
plt.ylabel('Cost')